config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :lots, only: [:show,:new,:create,:edit,:update] do
    resources :bids, only: [:show,:new,:create]
  end
  resources :products, only: [:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bid.rb
class Bid < ApplicationRecord
end

app/models/lot.rb
class Lot < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :cpf, presence: true
  # validates :cpf,  length: { is: 11 }

  def cpf_valid?
    return false if cpf_has_not_only_number
    cpf_is_OK
  end

  def cpf_has_not_only_number
    digits = cpf.split("")
    digits.select {|z| %w(0 1 2 3 4 5 6 7 8 9).include? z}.size == 11
  end

  def cpf_is_OK
    cpf_digits = cpf.split("")[0..8]
    sequence = [10,9,8,7,6,5,4,3,2]
    index = 0
    dig_sum = 0
    cpf_digits.each do |cpf_d|
      dig_sum = dig_sum + cpf_d.to_i * sequence[index]
      index = index + 1
    end
    #subtrair o resto da divisão por 11 do número 11
    sub_11 = 11 - (dig_sum % 11)
    #primeiro dígito verificador
    first_ver = 0
    if sub_11 < 10
      first_ver = sub_11
    else
      first_ver = 0
    end
    
    #dez primeiros dígitos * sequência de 11 à 2 
    #e somamos esse resultado
    cpf_digits = cpf.split("")[0..9]
    sequence = [11,10,9,8,7,6,5,4,3,2]
    index = 0
    dig_sum = 0
    cpf_digits.each do |cpf_d|
      dig_sum = dig_sum + cpf_d.to_i * sequence[index]
      index = index + 1
    end
    #subtrair o resto da divisão por 11 do número 11
    sub_11 = 11 - (dig_sum % 11)
    #primeiro dígito verificador
    second_ver = 0
    if sub_11 < 10
      second_ver = sub_11
    else
      second_ver = 0
    end

    #confirmação dos primeiro e segundo digitos verificadores
    first_OK = (cpf.split("")[9].to_i == first_ver)
    second_OK = (cpf.split("")[10].to_i == second_ver)    
    status_OK = (first_OK) && (second_OK)
  end
               
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:cpf])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:cpf])
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create]

  def show
    @bids = Bid.all
  end

  def new  
    @bid = Bid.new
    @bid.lots << @lot.code
  end

  def create
    @bid = Bid.new(bid_params)

    if @bid.save
      flash[:notice] = "Lance feito com sucesso!"
      redirect_to lot_path(@bid)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def bid_params
      params.require(:bid).permit(:lot_code, :cpf, :bid_value)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index  
    lots_all = Lot.all

    @lots = []
    @next_lots = []
    @out_lots = []
    today = DateTime.now.to_date
    lots_all.each do |l|
      start_date = l.start_date.to_date             
      if start_date.after? today
        @next_lots << l 
      else
        end_date = l.end_date.to_date
        if end_date.before? today
          @out_lots << l 
        else
          @lots << l
        end
      end      
    end


  end  
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  def show
    @lot = Lot.find(params[:id])
  end

  def new
    @lot = Lot.new
  end

  def create
    @lot = Lot.new(lot_params)

    if @lot.save
      flash[:notice] = "Lote cadastrado com sucesso!"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def lot_params
      params.require(:lot).permit(:code, :end_date, :minimum_value, :items, :start_date)
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      #flash[:notice] = "Produto cadastrado com sucesso!"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :photo, :weight, :dimensions, :product_category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bids/new.html.erb
<h2>Registrando um lance</h2>

<%= form_with model: @bid do |f| %>
    <div>
        <%= f.label :lot_code, "Código do lote" %>
        <%= f.text_field :lot_code %>
    </div>

    <div>
        <%= f.label :cpf, "CPF" %>
        <%= f.text_field :cpf %>
    </div>

    <div>
        <%= f.label :bid_value, "Valor do lance" %>
        <%= f.text_field :bid_value %>
    </div>

    <div>
        <%= f.submit "Enviar" %>
    </div>
    
<%end%>

app/views/bids/show.html.erb
<h3>Validação do Lance Vencedor</h3>

<% if @bids.any? %>
  <h3>Lote <%= @bids.last.lot_code %></h3>  
  <div>      
    <p>CPF vencedor: <%= @bids.last.cpf %></p>
    <p>valor do lance: <%= @bids.last.bid_value %></p>      
  </div>    
<% else %>
    <p>Vencedor CPF: Nenhum</p>
<% end %>  

<div>
  <%= button_to 'Encerrar lote', edit_lot_path %>  
</div>

app/views/home/index.html.erb
<div>
  <ul>
    <li><%= link_to 'Configurar Lote', new_lot_path%></li>
    <li><%= link_to 'Cadastrar Produtos', new_product_path %></li>
    <li><%= link_to 'Ver lotes vencidos' %></li>
    <li><%= link_to 'Lotes aguardando aprovação' %></li>
  </ul>
</div>

<section id="bidlots">
  <h4>Lotes disponíveis para lances:</h4>
  <div>
    <% @lots.each do |l| %>
      <p> 
        código: <%= link_to l.code, lot_path(l.id) %> 
        , lances a partir de R$ <%= l.minimum_bid %>
      </p>     
    <% end %>
  </div>

  <div>
    <% if @lots.empty? %>
      <p>Não há lotes disponíveis.</p>
    <% end %>
  </div>
</section>


<section>
  <h4>Lotes disponíveis em breve:</h4>
  <div>
    <% @next_lots.each do |l| %>
      <p> código: <%= link_to l.code, lot_path(l.id) %> </p>      
    <% end %>
  </div>

  <div>
    <% if @next_lots.empty? %>
      <p>Não há lotes disponíveis.</p>
    <% end %>
  </div>
</section>

<% if user_signed_in? %>
  <section id="outlots">
    <h4>Lotes vencidos:</h4> 
    <% if @out_lots.empty? %>
      <div>
        <p>Não há lotes para exibir.</p>      
      </div>
    <% else %>    
      <div>
        <% @out_lots.each do |l| %>
          <p> código: <%= link_to l.code, lot_path(l.id) %> </p>      
        <% end %>
      </div>
    <% end %>    
  </section>          
<% end %>      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'Leilão de produtos', root_path %></h1>
      <nav>
        <% if user_signed_in? %>
          <%= current_user.email %>
          <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path %>
        <% end %>      
      </nav>
    </header>

    <main>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </main>  
  </body>
</html>

app/views/lots/new.html.erb
<h2> Cadastrando novo lote </h2>

<%= form_with model: @lot do |f| %>
  <div>
    <%= f.label :code, 'Código do Lote' %>
    <%= f.text_field :code %>
  </div>
  
  <div>
    <%= f.label :end_date, 'Data final' %>
    <%= f.text_field :end_date %>
  </div>
  
  <div>
    <%= f.label :minimum_bid, 'Lance mínimo' %>
    <%= f.text_field :minimum_bid %>
  </div>
  
  <div>
    <%= f.label :start_date, 'Data início' %>
    <%= f.text_field :start_date %>
  </div>

  <div>
    <%= f.label :items, 'Itens' %>
    <%= f.text_area :items %>
  </div>
  
  <div>
      <%= f.submit 'Enviar'%>
  </div>

<% end %>

app/views/lots/show.html.erb
<h3>Código do lote <%= @lot.code %> </h3>

<dl>
  <dt>Lista de produtos contidos nesse lote:</dt>
  <dd>..</dd>
  <dt>'Lance inicial (R$): --'</dt>
  <dd>ler do model Bid</dd>
  <dt>data início do leilão: </dt> 
  <dd><%= @lot.start_date%></dd>
  <dt>data final para fazer lances: </dt>
  <dd><%= @lot.end_date%></dd>
</dl>

<% if @lot.start_date.to_date.before? DateTime.now.to_date %>
  <div>
    <%= link_to 'Fazer um lance', new_lot_bid_path(@lot) %></p>
  </div>
<% end %>

<div>
  <%= link_to 'Voltar', root_path %>
</div>

app/views/products/new.html.erb
<h2>Cadastro de Itens para Lotes</h2>

<%= form_with model:@product do |f| %>
  
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :photo, 'Foto' %>
    <%= f.file_field :photo %>
  </div>

  <div>
    <%= f.label :weight, 'Peso' %>
    <%= f.text_field :weight %>
  </div>

  <div>
    <%= f.label :dimensions, 'Dimensões em cm (largura, altura e profundidade)' %>
    <%= f.text_field :dimensions %>
  </div>

  <div>
    <%= f.label :product_category, 'Categoria de produto' %>
    <%= f.text_field :product_category %>
  </div>

  <div>
    <%= f.submit 'Cadastrar' %>
  </div>

<% end %>